import Head from 'next/head'
import Image from 'next/image'
import Mainpage from '../components/Mainpage'
import Musicplayer from '../components/Musicplayer'
import Sidebar from '../components/Sidebar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.inner}>
        <Sidebar />
        <Mainpage />
      </div>

      <div>
        <Musicplayer />
      </div>
    </div>
  )
}
